<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Who a batch of codes was handed to.
     *
     * Soft deletes, because a partner is the attribution on every code it was given.
     * Removing one from the picker must not take the name off last month's report, and a
     * code whose partner is deleted keeps pointing at the row, so the name it was handed
     * out under survives.
     *
     * One live name per campaign is a database guarantee, not only a validation rule. Two
     * requests naming the same new partner can both pass validation, because each of them
     * reads the table before the other writes to it, and the loser of that race would
     * otherwise produce a second row with the same name: two identical entries on the
     * picker and a report that splits one partner's codes across both.
     *
     * The unique is on (campaign_id, live_name) rather than on (campaign_id, name),
     * because a soft-deleted row sits in the index with the rest and would hold a name
     * against the operator who had already removed it. live_name is the name while the
     * row is live and NULL once it is deleted, and a unique index treats NULLs as
     * distinct in both MySQL and SQLite, so deleted rows fall out of the index entirely
     * and release the name. Naming deleted_at in the index directly does not work: a live
     * row's deleted_at is NULL, and two NULLs are distinct there too, so the index would
     * admit the duplicate it exists to refuse, while two rows deleted in the same second
     * would share a timestamp and collide, failing the delete itself.
     *
     * Names are compared without regard to case. Two partners on one campaign whose names
     * differ only in case are a typo rather than two partners: an operator typing "vendor
     * a" at a booth means the "Vendor A" already on the picker, and letting both rows
     * exist splits that partner's codes across two lines of every report while giving the
     * picker two entries nobody can tell apart. The name is stored exactly as it was
     * typed; only the comparison folds.
     *
     * Saying so explicitly is what makes the two engines agree. MySQL's
     * utf8mb4_unicode_ci already compares this way, so on MySQL alone nothing here
     * changes, while SQLite compares text byte for byte and would accept the second row
     * and answer the validation rule's lookup with nothing found. The local suite then
     * demonstrates neither behaviour. Declaring the collation on both columns gives one
     * answer on both engines: `name` is what the validation rule reads, and `live_name` is
     * what the unique index is built on, so both layers have to fold.
     */
    public function up(): void
    {
        $collation = $this->caseInsensitiveCollation();

        Schema::create('partners', static function (Blueprint $table) use ($collation) {
            $table->ulid('id')->primary();
            // ULID, matching campaigns.id. A bigint here is accepted by SQLite and
            // rejected by MySQL, which is what SchemaIntegrityTest exists to catch.
            $table->foreignUlid('campaign_id')
                ->constrained()
                ->cascadeOnDelete();
            // The column the validation rule compares against, so its collation is what
            // decides whether the operator is told the name is taken.
            $table->string('name', 80)->collation($collation);
            // A short fixed list (App\Models\Partner::KINDS) held as a string with
            // application-level validation, so a sixth kind is not a migration. Nullable
            // because a partner added in a hurry at a booth is still worth recording.
            $table->string('kind', 32)->nullable();
            $table->string('notes')->nullable();
            $table->timestamps();
            $table->softDeletes();

            // Generated by the database rather than written by the application, so the
            // guarantee holds for a row inserted by a migration, a seeder or a console
            // one-liner, none of which go through the model.
            //
            // Carries the collation in its own right. An index uses the collation declared
            // on the column it is built from, not the one on the column the expression
            // reads, so leaving it off here would fold the rule and not the index.
            $table->string('live_name', 80)
                ->nullable()
                ->collation($collation)
                ->storedAs('case when deleted_at is null then name end');

            // Also the index the foreign key needs and the one the picker reads the
            // campaign's partners through: campaign_id leads it, so a separate index on
            // that column would be a second copy of the same prefix.
            $table->unique(['campaign_id', 'live_name']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('partners');
    }

    /**
     * The collation that folds case on the engine this is running against.
     *
     * Two engines run this application: MySQL in production and in CI's MySQL job, SQLite
     * for the local suite and for a self-hosted instance that has not been pointed at a
     * server. They spell the same intent differently, and neither accepts the other's
     * name for it.
     *
     * Case folding is ASCII on SQLite and Unicode on MySQL, so "VENDÖR" and "vendör" are
     * one name on MySQL and two on SQLite. SQLite has no built-in collation that folds
     * beyond ASCII, so the alternative is to fold nothing anywhere, which loses the
     * ordinary case this exists for. Anything else the engine may not support is left
     * alone rather than handed a collation name it would reject at migrate time.
     */
    private function caseInsensitiveCollation(): ?string
    {
        return match (Schema::getConnection()->getDriverName()) {
            'sqlite' => 'nocase',
            'mysql', 'mariadb' => 'utf8mb4_unicode_ci',
            default => null,
        };
    }
};
