<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUlids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\Exists;
use Illuminate\Validation\Rules\Unique;

/**
 * Who a batch of codes was handed to: a member of staff on a booth, another project, a
 * print run, a mailing.
 *
 * A partner belongs to one campaign. Comparing the same vendor across two events is a
 * report that joins by name, not a shared row, because the campaign is already the event
 * boundary and two events' numbers are not one denominator.
 */
class Partner extends Model
{
    use HasFactory;
    use HasUlids;
    use SoftDeletes;

    /**
     * The channel a partner represents.
     *
     * A short fixed list rather than free text: comparing channels after three events is
     * impossible once "booth", "Booth staff" and "staff (booth)" are all in the column. A
     * string column rather than a database enum, so a sixth kind is a change to this list
     * instead of a migration.
     */
    public const KINDS = ['staff', 'partner', 'mailing', 'print', 'other'];

    protected $guarded = [];

    protected $hidden = [
        'deleted_at',
        // The column the unique index is built on, generated by the database from name
        // and deleted_at. It is how the guarantee is enforced, not something an operator
        // set or would recognise.
        'live_name',
    ];

    public function campaign(): BelongsTo
    {
        return $this->belongsTo(Campaign::class);
    }

    public function codes(): HasMany
    {
        return $this->hasMany(Code::class);
    }

    /**
     * The rule that makes a partner id safe to accept from a request.
     *
     * Scoped to the campaign, so an id belonging to somebody else's campaign fails
     * validation rather than being stored, and a request cannot use the difference between
     * "invalid" and "accepted" to learn that an id exists. Scoped to live rows too: a
     * deleted partner is off the picker, so a post naming one is either stale or made up.
     */
    public static function assignableRule(Campaign $campaign): Exists
    {
        return Rule::exists('partners', 'id')
            ->where('campaign_id', $campaign->id)
            ->whereNull('deleted_at');
    }

    /**
     * The rule that tells an operator a name is taken, before the database refuses it.
     *
     * The guarantee itself is the unique index on (campaign_id, live_name); see the
     * migration. This rule is what turns it into a message on the form, because a
     * constraint violation is not something a person standing at a booth can act on.
     *
     * It cannot be the guarantee on its own. Two requests naming the same new partner
     * both read the table before either writes, so both pass this rule and the index is
     * what refuses the second write.
     *
     * Scoped whereNull('deleted_at') to match the index, so a name comes free again the
     * moment its partner is removed.
     *
     * Case is not part of the comparison. The rule reads partners.name, and that column is
     * declared with a case-folding collation on both engines the application runs on, so
     * "vendor a" finds the "Vendor A" already on the picker and the operator is told the
     * name is taken rather than given a second partner nobody can tell from the first. The
     * collation is what makes this true; see the migration for why it is declared there
     * rather than written into this rule.
     */
    public static function uniqueNameRule(Campaign $campaign, ?string $ignoreId = null): Unique
    {
        $rule = Rule::unique('partners', 'name')
            ->where('campaign_id', $campaign->id)
            ->whereNull('deleted_at');

        return $ignoreId === null ? $rule : $rule->ignore($ignoreId);
    }

    /**
     * The partner the campaign's most recent code was generated for, if it is still live.
     *
     * This is what the picker defaults to. Generating codes for one partner is a repeated
     * action at a booth, and the alternative default, "Unassigned", is the one value that
     * cannot be corrected later.
     */
    public static function lastUsedOn(Campaign $campaign): ?string
    {
        return Code::query()
            ->where('codes.campaign_id', $campaign->id)
            ->whereNotNull('codes.partner_id')
            // Live partners only. Defaulting the picker to a deleted one would put an id
            // in the form that its own validation rule rejects.
            ->whereHas('partner')
            ->orderByDesc('codes.id')
            // Clear the columns Code::$withCount injects. Counting rewards and claims to
            // read one foreign key is three queries' work for one value, and MySQL rejects
            // the mixture under only_full_group_by where an aggregate is involved.
            ->select([])
            ->selectRaw('codes.partner_id')
            ->value('codes.partner_id');
    }
}
